name: Update Docker and Deploy (Production)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-docker:
    uses: RDGAapp/nginx/.github/workflows/build_push.yml@main
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: update-docker
    uses: RDGAapp/docker-compose/.github/workflows/update.yml@main
    secrets:
      VDS_HOST: ${{ secrets.VDS_HOST }}
      VDS_USER: ${{ secrets.VDS_USER }}
      VDS_PASSWORD: ${{ secrets.VDS_PASSWORD }}
      VDS_PORT: ${{ secrets.VDS_PORT }}
